### ISSUE TITLE
RST_STREAM frame after some client request

### ISSUE THREAD

**Issue by lwlee2608** [eclipse-vertx/vertx-grpc#40]
Using this client code:
```java
client
  .request(server, GreeterGrpc.getSayHelloMethod()).compose(request -> {
    request.end(HelloRequest
      .newBuilder()
      .setName("Bob")
      .build());
    return request.response().compose(response -> response.last());
  }).onSuccess(reply -> {
    System.out.println("Received " + reply.getMessage());
  });
```
 I have observed that RST_STREAM (8) is being sent after each request. However, my understanding of the RST_STREAM frame is that it should only be used when there is an error that prevents the sender or receiver from completing a particular stream.

To confirm my understanding, I also used the older VertxGrpcStub and found no instances of RST_STREAM being used.

I attempted to change `request.end()` to `request.write()` but this did not resolve the issue. Is there a way to send a request without including the RST_STREAM frame?

To gain further insights, I also performed a debug session using [this unit test](https://github.com/eclipse-vertx/vertx-grpc/blob/main/vertx-grpc-it/src/test/java/io/vertx/grpc/it/ProxyTest.java#L35) to trace the code that produces the RST_STREAM frame. I think it probably comes from [here](https://github.com/eclipse-vertx/vertx-grpc/blob/main/vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientRequestImpl.java#L242).

**Comment by vietj** [comment]
thanks, it is a bug in `GrpcClientRequestImpl`, those reset frames should not be sent.

Netty HTTP/2 server ignores such frames them because they existed, I'm expecting other servers do the same.

this will be fixed soon, it should not happen.

**Comment by lwlee2608** [comment]
@vietj I've traced the code and found[ GrpcReadStreamBase.init()](https://github.com/eclipse-vertx/vertx-grpc/blob/ec2e0b81d6a36f071e83db749fc858ebcd0b7165/vertx-grpc-common/src/main/java/io/vertx/grpc/common/impl/GrpcReadStreamBase.java#L87) -> [GrpcClientResponse.handleEnd()](https://github.com/eclipse-vertx/vertx-grpc/blob/main/vertx-grpc-client/src/main/java/io/vertx/grpc/client/impl/GrpcClientResponseImpl.java#L69) is sending the reset frame. Hope it helps.
