### ISSUE TITLE
Error on documentation

### ISSUE THREAD

**Issue by ikstewa** [eclipse-vertx/vertx-grpc#44]
### Context

vertx-grpc documentation page is showing a rendering error for the new vertx-grpc-context-storage module

Last line on the page https://vertx.io/docs/vertx-grpc/java/

`Unresolved directive in index.adoc - include::storage.adoc[]`

![image](https://user-images.githubusercontent.com/990120/223548145-6e53d7bb-9170-4753-b6a3-8dc99e5cc986.png)

**Comment by tsegismont** [comment]
> Need to cherry-pick [vert-x3/vertx-stack@149b9fd](https://github.com/vert-x3/vertx-stack/commit/149b9fd0f598f0cafae7f2a5b3085cb4f5b424ec) to `4.x` branch when it's ready

And then to update the starter
