### ISSUE TITLE
gRPC Web

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-grpc#55]
Support [grpc-web protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) in Vert.x gRPC Server

**Comment by GregYeo** [comment]
The Spring Framework also has gRPC support modules but they are not implementing grpc-web itself.

But that can be run by [envoy proxy ](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_web_filter#config-http-filters-grpc-web).

I am introduced it for my client. And it works very well and gRPC server generally does not need to care how gRPC Web works.  If someone needs it right now. The envoy proxy is available right away. I put envoy proxy as side car of gRPC Server in AWS Fargate. So there is not so much tasks to do.

Nice proposal but gRPC Web is wrapper layer itself to use gRPC. So I think the middleware(or reverse proxy) is more reasonable solution for it until gRPC could support browser natively.

**Comment by vietj** [comment]
thanks for sharing your opinion @GregYeo
